### ISSUE TITLE
reCAPTCHA v3 integration

### ISSUE THREAD

**Issue by philmarc** [anhskohbo/no-captcha#124]
Any plans to integrate latest [Google reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3)?

**Comment by josiasmontag** [comment]
From the reCAPTCHA docs:

> reCAPTCHA v2 is not going away! We will continue to fully support and improve security and usability for v2.
> 
> reCAPTCHA v3 is intended for power users, site owners that want more data about their traffic, and for use cases in which it is not appropriate to show a challenge to the user.
> 
> For example, a registration page might still use reCAPTCHA v2 for a higher-friction challenge, whereas more common actions like sign-in, searches, comments, or voting might use reCAPTCHA v3

Not sure if it makes sense to integrate v3 in this package, because there are fundamental design differences. Most importantly you can take variable action based on the score instead of just a yes/no validation.

I have created a reCAPTCHA v3 package (for v3 only): https://github.com/josiasmontag/laravel-recaptchav3. Currently I am using v2 (with this package) and v3 in parallel, depending on the use case.

**Comment by martsie** [comment]
Aha this solves a problem I've been having. In the README it says to setup a recaptcha key so I set up a v3 one thinking that I should use the latest and it doesn't work. For future googlers if you get "ERROR for site owner: Invalid key type" create a v2 key.
