### ISSUE TITLE
laravel 10

### ISSUE THREAD

**Issue by JuliusSimanavicius** [anhskohbo/no-captcha#186]
Laravel 10 support needed

**Comment by WillemStruiksma** [comment]
Here also.

**Comment by Dem0seQuence** [comment]
Here as well

**Comment by chengkangzai** [comment]
I believe the code base is actually ready for laravel 10 due to the PR of #185 , just need to tag the new version so that packagist can detect the new dependencies  
Maybe @anhskohbo can help? 
Thanks in Advance.

For people who want to get a quick fix, just do 
```
"anhskohbo/no-captcha": "dev-master",
```
on your composer.json until the new version is flagged

**Comment by Khuthaily** [comment]
@anhskohbo, tagging is needed for the change to be recognized ... as suggested by @chengkangzai. Thank you.

**Comment by MeesterDev** [comment]
For anyone reading this before the issue is closed: a new version was tagged 4 days ago at the time of this comment.

**Comment by ManelRosPuig** [comment]
Here too 😂

**Comment by JuliusSimanavicius** [comment]
working
